### ISSUE TITLE
Epaaaa

### ISSUE THREAD

**Issue by defcxz** [Coragg/POO-python#1]
Estaba revisando la pantalla principal de Github y me salió que comenzaste con este proyecto. Mucha suerte compañerooo

**Comment by Coragg** [comment]
No es un proyecto, son apuntes de unos estudios de programacion orientada objetos con python que estoy haciendo

**Comment by defcxz** [comment]
Ah bueno, suerte igualmente fsldkfslj

**Comment by Coragg** [comment]
Arigato
